### ISSUE TITLE
Date differences for differents dalles  

### ISSUE THREAD

**Issue by jhemmi** [olivierhagolle/theia_download#11]
Sources **from theia_download option list** 
Product T31TCJ is present on 20190401 then 20190501
but T31UEQ is present on four dates during the same april 2019
A cloud percent ? a problem during acquisition ?

T30TYP has no data from february 2019 to now.

Just another precision. Sentinel2 products have very stable hour of acquisition. It will be allways near 12h locale for France ?

**Comment by olivierhagolle** [comment]
Hi,
 we only deliver L2A products if their cloud cover is less than 90%, that's why some dates are missing. This saves computing time, disk space and bandwidth. 

April has been quite cloudy in the South West of France.

Regarding T30TYP, there is more than what you found:
https://theia.cnes.fr/atdistrib/rocket/#/search?page=1&collection=SENTINEL2&processingLevel=LEVEL2A&location=T30TYP

Yes, the overpass time should be quite stable, around 10h30 local time (=2hours for our time zone). There is a little difference (~15mn} depending on the acquisition is obtained from the west or the east
Olivier

**Comment by jhemmi** [comment]
Thanks for your qhick answers.
Regarding T30TYP, i was looking for a specific orbit ! User Error.
