### ISSUE TITLE
Method apply to SRE/FRE ?

### ISSUE THREAD

**Issue by jhemmi** [olivierhagolle/theia_download#9]
Can you explain method to calculate FRE versus SRE ?   
In which cases do you advice SRE/FRE ? 
I have not find any difference in my small area studies.

_I'am not sure to be in the right place for this question_

**Comment by olivierhagolle** [comment]
Hi,
FRE (Flattened  surface REflectance) products account for the variations of illumination as a function of the slope, while SRE (Surface REflectance) just process the data as if tehre was no elevation variations. Some users seem to prefer doing their own correction of terrain effects with their own accurate DEM, that's why we provide both products.  

On the terrain effect correction, you may read : http://www.cesbio.ups-tlse.fr/multitemp/?p=2481
Best regards,
Olivier

**Comment by jhemmi** [comment]
Thanks for your precision.
Merci
